version: 2.1

orbs:
  node: circleci/node@7

workflows:
  version: 2.1
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/node:24.9.0
    steps:
      - checkout
      - node/install-packages:
          package-manager: yarn
      - run: yarn test
