version: 2.1

orbs:
  node: circleci/node@7

workflows:
  version: 2.1
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/node:24.9.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
